import assert from 'node:assert/strict';
import {vehiclePosition,validateLiving} from '../web/pilot/living-core.js';
const lane={start:[100,100],end:[500,500],offsets:[.1,.6]};
const a=vehiclePosition(lane,0,.1),b=vehiclePosition(lane,0,.6);
assert.ok(a.xy.every(v=>Math.abs(v-140)<1e-8));assert.ok(b.xy.every(v=>Math.abs(v-340)<1e-8));
assert.equal(vehiclePosition(lane,0,0).alpha,0);
assert.ok(vehiclePosition(lane,10,.1).xy[0]>a.xy[0]);
assert.equal(vehiclePosition(lane,Math.hypot(400,400)/28,0).alpha,0);
validateLiving({});
assert.throws(()=>validateLiving({traffic:{lanes:[lane],speed:28,occluders:[]}}));
assert.throws(()=>validateLiving({landmark:{id:'x'},spots:[],occluders:[]}));
console.log('Living core: direction, spacing, wrap/fade, optional data and validation passed');
