'use strict';
const canvas=document.querySelector('#map'),ctx=canvas.getContext('2d');
let manifest,poi,W,H,DPR=1,z=0,cx=0,cy=0,drag=null,showPoi=true,token=0,style='baseline';
const cache=new Map(), colors={museum:'#ffcf67',market:'#ff7f72',tourinfo:'#6ed6bd'};
function scale(){return 2**(z-manifest.max_zoom)}
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;draw()}
function clamp(){const s=scale(),mw=manifest.width*s,mh=manifest.height*s;cx=Math.max(Math.min(cx,mw/2+W/2),Math.min(mw/2,W/2));cy=Math.max(Math.min(cy,mh/2+H/2),Math.min(mh/2,H/2))}
function tileUrl(x,y){return `${manifest.styles[style]}/${z}/${x}/${y}.png`}
function imageFor(url){if(cache.has(url))return cache.get(url);const im=new Image();im.onload=draw;im.src=url;cache.set(url,im);return im}
function point(xy){const s=scale();return [W/2+(xy[0]*s-cx),H/2+(xy[1]*s-cy)]}
function marker(p,color){const [x,y]=point(p.xy);if(x<-10||y<-10||x>W+10||y>H+10)return;ctx.fillStyle=color;ctx.fillRect(Math.round(x)-3,Math.round(y)-7,7,7);if(z>=manifest.max_zoom-1&&p.name){ctx.font='11px system-ui';ctx.strokeStyle='#000';ctx.lineWidth=3;ctx.strokeText(p.name,x+6,y-2);ctx.fillStyle='#fff';ctx.fillText(p.name,x+6,y-2)}}
function overlay(){if(!showPoi)return;ctx.save();ctx.setTransform(DPR,0,0,DPR,0,0);for(const k of Object.keys(colors))for(const p of poi[k])marker(p,colors[k]);for(const p of poi.subway.stations)marker(p,'#fff');ctx.restore()}
function draw(){if(!manifest)return;const my=++token;clamp();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#1a1e26';ctx.fillRect(0,0,canvas.width,canvas.height);const ts=manifest.tile_size,levelW=Math.ceil(manifest.width/2**(manifest.max_zoom-z)),levelH=Math.ceil(manifest.height/2**(manifest.max_zoom-z));const ox=W/2-cx,oy=H/2-cy;const x0=Math.max(0,Math.floor(-ox/ts)),y0=Math.max(0,Math.floor(-oy/ts)),x1=Math.min(Math.ceil(levelW/ts),Math.ceil((W-ox)/ts)),y1=Math.min(Math.ceil(levelH/ts),Math.ceil((H-oy)/ts));ctx.setTransform(DPR,0,0,DPR,0,0);ctx.imageSmoothingEnabled=false;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const im=imageFor(tileUrl(x,y));if(im.complete&&im.naturalWidth)ctx.drawImage(im,ox+x*ts,oy+y*ts)}if(my===token)overlay();document.querySelector('#status').textContent=`줌 ${z}/${manifest.max_zoom} · ${Math.round(cx/scale())}, ${Math.round(cy/scale())}`}
function setZoom(n,ax=W/2,ay=H/2){n=Math.max(0,Math.min(manifest.max_zoom,n));if(n===z)return;const old=scale(),wx=(ax-W/2+cx)/old,wy=(ay-H/2+cy)/old;z=n;const s=scale();cx=wx*s-(ax-W/2);cy=wy*s-(ay-H/2);draw();hash()}
function hash(){history.replaceState(null,'',`#${z},${Math.round(cx)},${Math.round(cy)},${style}`)}
function readHash(){const m=location.hash.match(/^#(\d+),(-?\d+),(-?\d+)(?:,(baseline|diorama))?$/);if(!m)return false;const v=m.slice(1,4).map(Number);if(!v.every(Number.isSafeInteger))return false;z=Math.max(0,Math.min(manifest.max_zoom,v[0]));cx=v[1];cy=v[2];if(m[4]&&manifest.styles[m[4]])style=m[4];return true}
function selectStyle(value){if(!manifest.styles[value])return;style=value;document.querySelector('#style').value=style;draw();hash()}
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,cx,cy];canvas.setPointerCapture(e.pointerId);canvas.classList.add('drag')};canvas.onpointermove=e=>{if(!drag)return;cx=drag[2]-(e.clientX-drag[0]);cy=drag[3]-(e.clientY-drag[1]);draw()};canvas.onpointerup=()=>{drag=null;canvas.classList.remove('drag');hash()};canvas.onwheel=e=>{e.preventDefault();setZoom(z+(e.deltaY<0?1:-1),e.clientX,e.clientY)};
canvas.onpointercancel=canvas.onpointerup;
document.querySelector('#style').onchange=e=>selectStyle(e.target.value);
document.querySelector('#in').onclick=()=>setZoom(z+1);document.querySelector('#out').onclick=()=>setZoom(z-1);document.querySelector('#poi').onchange=e=>{showPoi=e.target.checked;draw()};addEventListener('resize',resize);
Promise.all([fetch('tiles/manifest.json').then(r=>{if(!r.ok)throw Error('지도 타일이 없습니다. 생성 상태를 확인해주세요.');return r.json()}),fetch('data/generated/poi.json').then(r=>{if(!r.ok)throw Error('POI 데이터를 불러올 수 없습니다.');return r.json()})]).then(v=>{[manifest,poi]=v;manifest.styles=manifest.styles||{baseline:'tiles'};style=manifest.styles[manifest.default_style]?manifest.default_style:'baseline';z=Math.max(0,manifest.max_zoom-2);cx=manifest.width*scale()/2;cy=manifest.height*scale()/2;readHash();const picker=document.querySelector('#style');for(const key of Object.keys(manifest.styles)){const option=document.createElement('option');option.value=key;option.textContent=key==='diorama'?'서울 디오라마':'기존';picker.append(option)}picker.value=style;picker.disabled=Object.keys(manifest.styles).length<2;document.querySelector('#load').remove();resize()}).catch(e=>{document.querySelector('#load').textContent=e.message});
